# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build-win64:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: "18.x"

            - name: Install Linux dependencies
              run: sudo apt install wine -y

            - name: Install Node.js dependencies
              run: npm ci

            - name: Build
              run: npm run-script dist:64

            - name: Upload artifacts
              uses: actions/upload-artifact@v3.1.0
              with:
                name: app.asar
                path: dist/linux-unpacked/resources/app.asar
