name: Update package-lock.json

on:
    workflow_dispatch:

jobs:
    windows-build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Update lock file
              run: npm install --package-lock-only

            - name: Run audit fix
              run: npm audit fix

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: artifacts
                path: |
                  package-lock.json
